#!/bin/sh

set -e

export PYTHONPATH=$PYTHONPATH:/home/james/local/lib/python2.4
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/james/local/lib

cd /home/james

cp -a .woodpecker/last-index .woodpecker/tmp-index
touch .woodpecker/last-index
find mail -mindepth 2 -type f -newer .woodpecker/tmp-index -print0 | xargs -0 python projects/sja/woodpecker/woodpecker.py -q
rm .woodpecker/tmp-index
